# Generated by Django 5.1.7 on 2025-08-21 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_activitylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ActivityLog',
        ),
    ]
