# Generated by Django 5.1.7 on 2025-12-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_transaction_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wallet_balance',
        ),
    ]
