# Generated by Django 5.1.7 on 2025-12-18 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
